# Railway.toml - Configuration for Rockfish deployment

[build]
builder = "nixpacks"
buildCommand = "pip install -r rockfish/requirements.txt"

[deploy]
startCommand = "streamlit run rockfish/src/app.py --server.port=$PORT --server.address=0.0.0.0"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
